<?php
require './config.php';
require './functions.php';
require 'Pepipopum.php';

header('Content-type: text/html; charset=utf-8');

function processForm()
{
    set_time_limit(86400); // Set the number of seconds a script is allowed to run

    if ($_POST['output'] == 'html')
    {
        //we output to a temporary file to allow later download
        echo '<h1>Processing PO file...</h1>';
        echo '<div id="info"></div>';
        $outfile = tempnam(sys_get_temp_dir(), 'pepipopum');
    }
    else
    {
        //output directly
        header("Content-Type:text/plain");
        $outfile = "php://output";
    }
	
	$data = file_get_contents($_FILES['pofile']['tmp_name']);

    $translator = new Pepipopum();
	$translator->debug = true;
	$translator->logfile = './pepipopum.debug.' . time() . '.log';
	$translator->languageIn = 'en';
	$translator->languageOut = $_POST['language'];
    $translated = $translator->translate($data);
	
	file_put_contents($outfile, $translated);


    if ($_POST['output'] == 'html')
    {
        //show download link
        $leaf = basename($outfile);
        $name = $_FILES['pofile']['name'];

        echo "Completed - <a href=\"pepipopum.php?download=".urlencode($leaf)."&name=".urlencode($name)."\">download your updated po file</a>";
    }
    else
    {
        //we're done
        exit;
    }
}

if (isset($_GET['download']) && isset($_GET['name']))
{
    //check download file is valid
    $file = sys_get_temp_dir().DIRECTORY_SEPARATOR.$_GET['download'];
    $ok = preg_match('/^pepipopum[A-Za-z0-9]+$/', $_GET['download']);
    $ok = $ok && file_exists($file);

    //sanitize name
    $name = preg_replace('/[^a-z0-9\._]/i', '', $_GET['name']);

    if ($ok)
    {
        header("Content-Type:text/plain");
        header("Content-Length:".filesize($file));
        header("Content-Disposition: attachment; filename=\"{$name}\"");

        readfile($file);
    }
    else
    {
        //fail
        header("HTTP/1.0 404 Not Found");
        echo "The requested pepipopum output file is not available - it may have expired. <a href=\"pepipopum.php\">Click here to generate a new one</a>.";
    }
    exit;
}

if (isset($_POST['output']) && ($_POST['output'] == 'pofile'))
{
    processForm();
}

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
<title>Pepipopum - Translate PO file with Google Translate</title>
<style type="text/css">


body
{
    background:#eeeeee;
    margin: 0;
    padding: 0;
    text-align: center;

    font-family:Verdana,Arial,Helvetica
}

#main
{
    padding: 3em;
    margin: 1em auto 1em auto;
    width: 50em;
    border:1px solid #dddddd;
    text-align: left;
    background:white;
}

#footer
{
    text-align:right;
    font-size:8pt;
    color:#888888;
    border-top:1px solid #888888;
}

h1
{
    margin-top:0;
}

form
{
    background:#dddddd;
    padding:2em;
    margin:0 2em 0 2em;

    -moz-border-radius: 1em;
    -webkit-border-radius: 1em;
    border-radius: 1em;

    font-size:0.8em;
}

fieldset
{
    background:#cccccc;
    border:1px solid #aaaaaa;
    margin-bottom:1em;
    padding:1em;
    position:relative;

    -moz-border-radius: 0.5em;
    -webkit-border-radius: 0.5em;
    border-radius: 0.5em;

}

legend
{
    background:#aaaaaa;
    border:0;
    padding:0 1em 0 1em;
    margin-left:1em;
    color:#ffffff;

    position: absolute;
    top: -1.5em;
    left: .2em;


    -moz-border-radius: 0.5em;
    -webkit-border-radius: 0.5em;
    border-radius: 0.5em;

}

</style>
</head>

<body>
<div id="main">

<?php
if (isset($_POST['output']) && ($_POST['output'] == 'html'))
{
    processForm();
}
?>

<h1>Pepipopum - Translate PO files with Google Translate</h1>

<p>PO files originate from the <a href="http://www.gnu.org/software/gettext/gettext.html">GNU gettext</a>
tools and can be generated by a wide variety of other localization tools.</p>

<p>Pepipopum allows you to upload a PO file containing English language strings in the <i>msgid</i>,
and it uses the <a href="http://code.google.com/apis/ajaxlanguage/">Google Translate API</a>
to construct a PO file containing translated equivalents in each corresponding <i>msgstr</i></p>

<p>If the PO file already contains a translation for a given msgid, it will not be translated. This
allows you to upload a proof-read PO and just get translations for any new elements.</p>

<form enctype="multipart/form-data" action="pepipopum.php" method="post">

     <fieldset>
    <legend>Input</legend>
       <div class="field">
        <div class="label"><label for="pofile">PO File</label></div>
        <div class="input"><input id="pofile" name="pofile" type="file" /></div>
        </div>
    </fieldset>

    <fieldset>
    <legend>Output options</legend>

 <div class="field">
        <div class="label"><label for="language">Target Language</label></div>
        <div class="input"><select id="language" name="language">
            <option value="af">Afrikaans</option>
            <option value="sq">Albanian</option>
            <option value="ar">Arabic</option>
            <option value="be">Belarusian</option>
            <option value="bg">Bulgarian</option>
            <option value="ca">Catalan</option>
            <option value="zh-CN">Chinese (Simplified)</option>
            <option value="zh-TW">Chinese (Traditional)</option>
            <option value="hr">Croatian</option>
            <option value="cs">Czech</option>
            <option value="da">Danish</option>
            <option value="nl">Dutch</option>
            <option value="en">English</option>
            <option value="et">Estonian</option>
            <option value="tl">Filipino</option>
            <option value="fi">Finnish</option>
            <option value="fr">French</option>
            <option value="gl">Galician</option>
            <option value="de">German</option>
            <option value="el">Greek</option>
            <option value="iw">Hebrew</option>
            <option value="hi">Hindi</option>
            <option value="hu">Hungarian</option>
            <option value="is">Icelandic</option>
            <option value="id">Indonesian</option>
            <option value="ga">Irish</option>
            <option value="it">Italian</option>
            <option value="ja">Japanese</option>
            <option value="ko">Korean</option>
            <option value="lv">Latvian</option>
            <option value="lt">Lithuanian</option>
            <option value="mk">Macedonian</option>
            <option value="ms">Malay</option>
            <option value="mt">Maltese</option>
            <option value="no">Norwegian</option>
            <option value="fa">Persian</option>
            <option value="pl">Polish</option>
            <option value="pt">Portuguese</option>
            <option value="ro">Romanian</option>
            <option value="ru">Russian</option>
            <option value="sr">Serbian</option>
            <option value="sk">Slovak</option>
            <option value="sl">Slovenian</option>
            <option value="es">Spanish</option>
            <option value="sw">Swahili</option>
            <option value="sv">Swedish</option>
            <option value="th">Thai</option>
            <option value="tr">Turkish</option>
            <option value="uk">Ukrainian</option>
            <option value="vi">Vietnamese</option>
            <option value="cy">Welsh</option>
            <option value="yi">Yiddish</option>
            </select>
        </div>
     </div>

     <div>
     <input id="output_po" name="output" value="pofile" type="radio"/>
     <label for="output_po">Output PO File</label>
     </div>

     <div>
     <input id="output_html" name="output" value="html" checked="checked" type="radio"/>
     <label for="output_html">Output progress meter and then provide a download link</label>
     </div>
     </fieldset>

    <div>
    <input type="submit" value="Translate File" />
    </div>

</form>

<p>You can automate translation by using a tool like <a href="http://curl.haxx.se/">cURL</a> to post a PO file and obtain
a translated result. For example:</p>

<pre>
    curl -F pofile=@<i>input-po-filename</i> \
        -F language=<i>target-language-code</i> \
        -F output=pofile
        http://pepipopum.dixo.net \
        --output <i>output-po-filename</i>

</pre>


<p>Why is called "Pepipopum"? I just invented a word which had
'po' in it and was relatively rare on Google! Pronounce it <i>pee-pie-poe-pum</i>.</p>

<p><a href="http://blog.dixo.net/2009/10/24/pepipopum-automatically-translate-po-files-with-google-translate/">Comments and suggestions</a> are welcome.</p>
<div id="footer">
<p><a href="http://blog.dixo.net/about">(c)2009 Paul Dixon</a></p>
</div>
</div>
</body>
</html>
